### ISSUE TITLE
On flip the block trend should be (1 - previous candidate block trend).

### ISSUE THREAD

**Issue by berendjan** [alex/nyt-2020-election-scraper#210] opened 2020-11-06 09:54 UTC

**Comment by Enivex** [comment] 2020-11-06 09:57
This would break after another update if it doesn't cross 30k votes. The more robust solution is to recompute the moving average for the new leader.

**Comment by conerck** [comment] 2020-11-06 10:05
Block Breakdown is also incorrect.

In the flip Biden scored 1602 Votes, Trump scored 222.
The breakdown is 87.8% Biden / 12.2% Trump, not  Biden 62.3% / 37.7% Trump as displayed.

**Comment by hugovk** [comment] 2020-11-06 10:09
Duplicate of #210 etc.

**Comment by devon-badman** [comment] 2020-11-06 10:29
Issue is that in print-battleground-state-changes

`def compute_hurdle_sma( ...  `
`   ...  `
`   agg_c2_votes += round(this_summary.trailing_candidate_partition * this_summary.new_votes * subset_pct)`

always assumes that the trailing candidates votes are in the trailing candidate column, which is incorrect. 

When iterating over the last N updates, the code needs to define on the first pass who the trailing candidate is, then every iteration after that use that candidates vote count, not blindly look in the trailing column.

**Comment by frewsxcv** [comment] 2020-11-06 12:20
thanks for the bug report! this is now fixed by https://github.com/alex/nyt-2020-election-scraper/pull/215

**Closed as completed by frewsxcv** 2020-11-06 12:20 UTC
