### ISSUE TITLE
Wrong block breakdown when crossing 0?

### ISSUE THREAD

**Issue by lshh125** [alex/nyt-2020-election-scraper#220] opened 2020-11-06 10:22 UTC
It seems that the breakdown is based on the difference between consecutive vote differentials, but when it crosses 0 (e.g., at the time GA turned blue), it should be sum instead of difference (i.e., 917+463 instead of 917-463). Seems to be a bug in current version.

Thanks for the great tool.

**Comment by AgentAntelope** [comment] 2020-11-06 10:27
Adding screenshot 
![image](https://user-images.githubusercontent.com/1962412/98355833-9cfd0c00-201a-11eb-8489-3d66402d6d4b.png)

**Comment by AgentAntelope** [comment] 2020-11-06 10:29
Adding a screenshot of the rows in question. 
![image](https://user-images.githubusercontent.com/1962412/98356030-e3526b00-201a-11eb-8898-0365e6eefd16.png)

**Comment by emclain** [comment] 2020-11-06 10:30
Duplicate of #210

**Comment by spraot** [comment] 2020-11-06 11:02
Fixed by #215

**Comment by frewsxcv** [comment] 2020-11-06 12:19
thanks for the bug report! this is now fixed by https://github.com/alex/nyt-2020-election-scraper/pull/215

**Closed as completed by frewsxcv** 2020-11-06 12:19 UTC
