### ISSUE TITLE
Incorrect Label for Trump But Great Work!

### ISSUE THREAD

**Issue by adamm522** [alex/nyt-2020-election-scraper#218] opened 2020-11-06 10:09 UTC
Incorrect label in data pull.

Block Trend should read: 

"Biden is averaging 65.6%"

not       
     
"Trump is averaging 65.6%"
       
![Screen Shot 2020-11-06 at 11 06 51 AM](https://user-images.githubusercontent.com/32357206/98354039-793cc480-2020-11eb-9f51-4c51dba360d1.png)

**Comment by alex-quin-gabriel** [comment] 2020-11-06 10:11
You beat me to it :)

**Comment by hugovk** [comment] 2020-11-06 10:12
Duplicate of #210 etc.

**Comment by louispires** [comment] 2020-11-06 10:12
The label is correct, when Trump leads then it states how much Biden is trending at.

Now when Biden leads it should state how much trump is trending at. 

Thus the label is correct but the value is wrong

**Comment by sallymatson** [comment] 2020-11-06 10:14
+1!!

**Comment by frewsxcv** [comment] 2020-11-06 12:19
thanks for the bug report! this is now fixed by https://github.com/alex/nyt-2020-election-scraper/pull/215

**Closed as completed by frewsxcv** 2020-11-06 12:19 UTC
