### ISSUE TITLE
Block Trend is reversed when state switches lead candidate

### ISSUE THREAD

**Issue by phdowling** [alex/nyt-2020-election-scraper#216] opened 2020-11-06 10:02 UTC
Hi, great tool! Noticed this glitch just now:
<img width="1420" alt="Screenshot 2020-11-06 at 11 00 30" src="https://user-images.githubusercontent.com/876919/98353274-61187580-201f-11eb-8034-5d010bd08fa9.png">
It looks like the block trend information is a bit off when the lead candidate switches.

**Comment by filbo** [comment] 2020-11-06 10:05
Ok, I guess I won't report that :)

**Comment by CennoxX** [comment] 2020-11-06 10:13
duplicate of #210

**Comment by frewsxcv** [comment] 2020-11-06 12:21
thanks for the bug report! this is now fixed by https://github.com/alex/nyt-2020-election-scraper/pull/215

**Closed as completed by frewsxcv** 2020-11-06 12:21 UTC
