### ISSUE TITLE
'Block Trend' column broke when GA flipped 

### ISSUE THREAD

**Issue by marioniepel** [alex/nyt-2020-election-scraper#228] opened 2020-11-06 11:45 UTC
Looks like the 'Block Trend' column broke when GA flipped from Trump to Biden. Should say 'Biden is averaging' or adjust the percentage to Trump.

![Screenshot 2020-11-06 064302](https://user-images.githubusercontent.com/5176275/98362554-6f549a80-1ffb-11eb-9e0b-315d2101c26d.png)

**Comment by spraot** [comment] 2020-11-06 11:50
This is a duplicate of #210, #216, #218, #220 and more. It's already fixed by #215

**Comment by tomglynch** [comment] 2020-11-06 12:01
@rachetfoot I don't think it's fully fixed. Says "Trump is averaging 65.1%" when it should be "Trump is averaging ~34%". Name has been correctly swapped but the percentage hasn't.

**Comment by spraot** [comment] 2020-11-06 12:05
@tomglynch The fix hasn't been merged yet.

**Comment by frewsxcv** [comment] 2020-11-06 12:18
thanks for the bug report! this is now fixed by https://github.com/alex/nyt-2020-election-scraper/pull/215

**Closed as completed by frewsxcv** 2020-11-06 12:18 UTC

**Comment by marioniepel** [comment] 2020-11-06 12:20
Thanks guys. I love this site! Great work.
